[package]
name = "wordle_grep"
version = "0.1.0"
edition = "2024"

[lib]
name = "wordle_grep"
path = "src/lib.rs"

[dependencies]
reqwest = { version = "0.13.1", features = ["blocking"] }
anyhow = "1.0"
ratatui = "0.30"
crossterm = "0.29"
rand = "0.8"
